LineFocus.Nikcron/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LineFocus.Nikcron.Controllers
{
    public class ServiceController : Controller
    {
        //
        // GET: /Service/

        public ActionResult Index()
        {
            return View();
        }

    }
}

LineFocus.Nikcron/Views/Service/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@model IEnumerable<Nickron.Database.Service>
@{

    <div class="col-lg-6">
        <ol class="breadcrumb">
            <li>@Html.ActionLink("New Service", "ServiceMaintenance", "Service", null, new { style = "float: right;" })</li>

        </ol>
    </div>

    <div class="col-xs-12">
        <div class="box">
            <div class="box-body table-responsive">
                <table id="example1" class="table table-bordered table-striped">

                    <thead>
                        <tr>
                            <th>Sno</th>
                            <th>Service Center</th>
                            <th>Staff Name</th>
                            <th>Service Date</th>
                            <th>Type</th>                            
                            <th>Edit | Delete | View</th>
                        </tr>
                    </thead>
                    <tbody>
                       
                            <tr>
                                <td>1</td>
                                <td>Tambaram</td>
                                <td>Jayenthan</td>
                                <td>01/07/2014</td>
                                <td>Service Type1</td>
                                <td>
                                    @Html.ActionLink("Edit", "ZoneMaintenance") |
                                    @Html.ActionLink("Delete", "Delete") |
                                    @Html.ActionLink("View", "ZoneMaintenance")
                                </td>
                            </tr>                        
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>Sno</th>
                            <th>Service Center</th>
                            <th>Staff Name</th>
                            <th>Service Date</th>
                            <th>Type</th>
                            <th>Edit | Delete | View</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>

}

LineFocus.Nikcron/Views/Service/ServiceMaintenance.cshtml
@{
    ViewBag.Title = "ServiceMaintenance";
}

@model Nickron.Database.Service

@using (Html.BeginForm("ServiceMaintenance", "Service", FormMethod.Post, new { onsubmit = "return ValidateForm();" }))
{
    <div class="col-md-6">

        <div class="box box-danger">
            <div class="box-body">

                <div class="form-group">
                    <label> IMEI No:</label><span class="astrisk">*</span>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i></i>
                        </div>
                        <input id="ImeiNo1" name="ImeiNo1" maxlength="250" type="text" class="form-control" />
                    </div><!-- /.input group -->
                </div><!-- /.form group -->

                <div class="box box-success">
                    <div class="box-footer">                       
                        <button type="submit" class="btn btn-primary" style=" width:80px;">Search</button>
                    </div>
                </div>

                <div class="form-group">
                    <label> IMEI NO2:</label><span class="astrisk">*</span>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class=""></i>
                        </div>                        
                        <label id="ImeiNo2" class="form-control"> </label>
                    </div><!-- /.input group -->
                </div><!-- /.form group -->
               
                <div class="form-group">
                    <label> Serial No:</label><span class="astrisk">*</span>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class=""></i>
                        </div>
                        <label id="ImeiNo2" class="form-control"> </label>
                    </div><!-- /.input group -->
                </div><!-- /.form group -->

                <div class="form-group">
                    <label> Sale On:</label><span class="astrisk">*</span>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class=""></i>
                        </div>
                        <label id="ImeiNo2" class="form-control"> </label>
                    </div><!-- /.input group -->
                </div><!-- /.form group -->

                <div class="form-group">
                    <span class="astrisk">*</span>
                    <label> Expiry:</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class=""></i>
                        </div>
                        <label id="ImeiNo2" class="form-control"> </label>
                    </div><!-- /.input group -->
                </div><!-- /.form group -->

                <div class="form-group">
                    <label> Model Type:</label><span class="astrisk">*</span>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class=""></i>
                        </div>
                        <label id="ImeiNo2" class="form-control"> </label>
                    </div><!-- /.input group -->
                </div><!-- /.form group -->

                <div class="form-group">
                    <label> Model No:</label><span class="astrisk">*</span>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i></i>
                        </div>
                        <label id="ImeiNo2" class="form-control"> </label>
                    </div><!-- /.input group -->
                </div><!-- /.form group -->

                <div class="form-group">
                    <label> Customer Name:</label><span class="astrisk">*</span>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i></i>
                        </div>
                        <label id="ImeiNo2" class="form-control"> </label>
                    </div><!-- /.input group -->
                </div><!-- /.form group -->

                <div class="form-group">
                    <label> Last service:</label><span class="astrisk">*</span>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i></i>
                        </div>
                        <label id="ImeiNo2" class="form-control"> </label>
                    </div><!-- /.input group -->
                </div><!-- /.form group -->

                <div class="form-group">
                    <label> service Count:</label><span class="astrisk">*</span>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i></i>
                        </div>
                        <label id="ImeiNo2" class="form-control"> </label>
                    </div><!-- /.input group -->
                </div><!-- /.form group -->

            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div>

    <div class="col-md-6">
        <div class="box box-primary">

            <div class="box-body">
              
                <div class="form-group">
                    <label> Service Center:</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class=""></i>
                        </div>
                        <select id="Servicecenter" name="Servicecenter" class="form-control">
                            <option value="0">---Select---</option>
                        </select>
                    </div><!-- /.input group -->
                </div><!-- /.form group -->

                <div class="form-group">
                    <label> Service Type:</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class=""></i>
                        </div>
                        <select id="Servicetype" name="Servicetype" class="form-control">
                            <option value="0">---Select---</option>
                        </select>
                    </div><!-- /.input group -->
                </div><!-- /.form group -->

                <div class="form-group">
                    <label> Faults:</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i></i>
                        </div>
                        <input id="Faults" name="Faults" type="text" maxlength="250" class="form-control pull-right" />
                    </div><!-- /.input group -->
                </div><!-- /.form group -->

                <div class="form-group">
                    <label> Accessories:</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i></i>
                        </div>
                        <textarea id="Accessories" name="Accessories" maxlength="500" class="form-control pull-right"></textarea>
                    </div><!-- /.input group -->
                </div><!-- /.form group -->

                <div class="form-group">
                    <label> Descriptions:</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i></i>
                        </div>
                        <textarea id="Descriptions" name="Email"  maxlength="500" class="form-control pull-right"></textarea>
                    </div><!-- /.input group -->
                </div><!-- /.form group -->           

               

            </div><!-- /.box-body -->
        </div><!-- /.box -->

        <div class="box box-success">
            <div class="box-footer">
                <input type="hidden" name="Id" id="Id" value="@ViewBag.Id" />
                <button type="submit" class="btn btn-primary" style=" width:80px;">Save</button>
                <button type="reset" class="btn btn-primary" style=" width:80px;">Cancel</button>
            </div>
        </div><!-- /.box -->
    </div>
}

<script type="text/javascript">
    function ValidateForm() {

        if (document.getElementById("Faults").value == "") {
            alert("Faults can't be empty!");
            document.getElementById("Faults").focus();
            return false;
        }
        if (document.getElementById("Descriptions").value == "") {
            alert("Descriptions can't be empty!");
            document.getElementById("Descriptions").focus();
            return false;
        }
    
       // RequiredTextbox("Company", "Enter the Company Name")
       // RequiredTextbox("ContactPerson", "Enter the Contact Person")
       // RequiredTextbox("Address1", "Enter the Address")
       // RequiredTextbox("City", "Enter the City")

        return AlertError();
    }
</script>