LineFocus.Nikcron/Controllers/PurchaseOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LineFocus.Nikcron.Controllers
{
    public class PurchaseOrderController : Controller
    {
        //
        // GET: /PurchaseOrder/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PurchaseOrderMaintenance()
        {
            return View();
        }

    }
}

LineFocus.Nikcron/Views/PurchaseOrder/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@model IEnumerable<Nickron.Database.Service>
@{

    <div class="col-lg-6">
        <ol class="breadcrumb">
            <li>@Html.ActionLink("New Purchase Order", "PurchaseOrderMaintenance", "PurchaseOrder", null, new { style = "float: right;" })</li>

        </ol>
    </div>

    <div class="col-xs-12">
        <div class="box">
            <div class="box-body table-responsive">
                <table id="example1" class="table table-bordered table-striped">

                    <thead>
                        <tr>
                            <th>Sno</th>
                            <th>Invoice No</th>
                            <th>Stockits</th>
                            <th>Purchase Date</th>
                            <th>Qtys</th>
                            <th>Edit | Delete | View</th>
                        </tr>
                    </thead>
                    <tbody>

                        <tr>
                            <td>1</td>
                            <td>10001</td>
                            <td>Surya.K</td>
                            <td>01/07/2014</td>
                            <td>20</td>
                            <td>
                                @Html.ActionLink("Edit", "ZoneMaintenance") |
                                @Html.ActionLink("Delete", "Delete") |
                                @Html.ActionLink("View", "ZoneMaintenance")
                            </td>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>10002</td>
                            <td>Harikumar.M</td>
                            <td>01/07/2014</td>
                            <td>50</td>
                            <td>
                                @Html.ActionLink("Edit", "ZoneMaintenance") |
                                @Html.ActionLink("Delete", "Delete") |
                                @Html.ActionLink("View", "ZoneMaintenance")
                            </td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>Sno</th>
                            <th>Invoice No</th>
                            <th>Stockits</th>
                            <th>Purchase Date</th>
                            <th>Qtys</th>
                            <th>Edit | Delete | View</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>

}

LineFocus.Nikcron/Views/PurchaseOrder/PurchaseOrderMaintenance.cshtml
@{
    ViewBag.Title = "PurchaseOrderMaintenance";
}

@model Nickron.Database.Service

@using (Html.BeginForm("PurchaseOrderMaintenance", "PurchaseOrder", FormMethod.Post, new { onsubmit = "return ValidateForm();" }))
{
 <div class="col-md-12">

        <div class="box box-danger">
            <div class="box-body">

                <div class="box-header">
                    <h3 class="box-title">New Purchase Order</h3>
                </div>

                <div class="form-group">
                    <label> Purchase No:</label><span class="astrisk">*</span>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i></i>
                        </div>
                        <input id="PurchaseNo" name="PurchaseNo" maxlength="250" type="text" class="form-control" />
                    </div><!-- /.input group -->
                </div><!-- /.form group -->

                <div class="form-group">
                    <label> StockIts:</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class=""></i>
                        </div>
                        <select id="Servicecenter" name="Servicecenter" class="form-control">
                            <option value="0">---Select---</option>
                        </select>
                    </div><!-- /.input group -->
                </div><!-- /.form group -->

                <div class="form-group">
                    <label> Product Type:</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class=""></i>
                        </div>
                        <select id="Servicetype" name="Servicetype" class="form-control">
                            <option value="0">---Select---</option>
                            <option value="1">Mobile</option>
                            <option value="2">Laptop</option>
                            <option value="3">Tablet</option>
                        </select>
                    </div><!-- /.input group -->
                </div><!-- /.form group -->

                <div class="form-group">
                    <label> Model Type:</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class=""></i>
                        </div>
                        <select id="Servicecenter" name="Servicecenter" class="form-control">
                            <option value="0">---Select---</option>
                        </select>
                    </div><!-- /.input group -->
                </div><!-- /.form group -->

                <div class="form-group">
                    <label> Model No:</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class=""></i>
                        </div>
                        <select id="Servicetype" name="Servicetype" class="form-control">
                            <option value="0">---Select---</option>                           
                        </select>
                    </div><!-- /.input group -->
                </div><!-- /.form group -->

                <div class="form-group">
                    <label> Color:</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class=""></i>
                        </div>
                        <select id="Servicetype" name="Servicetype" class="form-control">
                            <option value="0">---Select---</option>                          
                        </select>
                    </div><!-- /.input group -->
                </div><!-- /.form group -->

                <div class="form-group">
                    <label> Qty:</label><span class="astrisk">*</span>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class=""></i>
                        </div>
                        <input id="ImeiNo2" name="Qty" class="form-control"/>
                    </div><!-- /.input group -->
                </div><!-- /.form group -->    
            
                <div class="box box-success">
                    <div class="box-footer">                       
                        <button type="submit" class="btn btn-primary" style=" width:80px;">Add</button>
                        <button type="reset" class="btn btn-primary" style=" width:80px;">Clear</button>
                    </div>
                </div><!-- /.box -->   
            
                <div class="box-body table-responsive">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Sno</th>
                                <th>Product Type</th>
                                <th>Model Type</th>
                                <th>Model No</th>
                                <th>Coloe</th>
                                <th>Qty</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>

                            <tr>
                                <td>1</td>
                                <td>Mobile</td>
                                <td>Nokia</td>
                                <td>Lumiya 630</td>
                                <td>Green</td>
                                <td>15</td>
                                <td>
                                    @Html.ActionLink("Delete", "ZoneMaintenance")

                                </td>
                            </tr>
                            <tr>
                                <td>1</td>
                                <td>Laptop</td>
                                <td>Dell</td>
                                <td>Dell0011</td>
                                <td>Red</td>
                                <td>10</td>
                                <td>
                                    @Html.ActionLink("Delete", "ZoneMaintenance")

                                </td>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Sno</th>
                                <th>Product Type</th>
                                <th>Model Type</th>
                                <th>Model No</th>
                                <th>Coloe</th>
                                <th>Qty</th>
                                <th>Delete</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>

                <div class="box box-success">
                    <div class="box-footer">
                        <input type="hidden" name="Id" id="Id" value="@ViewBag.Id" />
                        <button type="submit" class="btn btn-primary" style=" width:80px;">Save</button>
                        <button type="reset" class="btn btn-primary" style=" width:80px;">Cancel</button>
                    </div>
                </div>
                   

            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col (left) -->
    
}

<script type="text/javascript">
    function ValidateForm() {

        if (document.getElementById("PurchaseNo").value == "") {
            alert("Purchase No can't be empty!");
            document.getElementById("PurchaseNo").focus();
            return false;
        }

        // RequiredTextbox("Company", "Enter the Company Name")
        // RequiredTextbox("ContactPerson", "Enter the Contact Person")
        // RequiredTextbox("Address1", "Enter the Address")
        // RequiredTextbox("City", "Enter the City")

        return AlertError();
    }
</script>