LineFocus.Nikcron/Controllers/DealerController.cs
using Nickron.Database;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LineFocus.Nikcron.Controllers
{
    public class DealerController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public JsonResult GetDealers()
        {
            throw new NotImplementedException();            
        }
        [HttpGet]
        public ActionResult Maintenance(Int32? DealerId)
        {
            if (DealerId.HasValue)
            {
                ApplicationDBContext db = new ApplicationDBContext();
                Dealers Dealer = db.Offices.OfType<Dealers>().Where(d => d.Id == DealerId).FirstOrDefault();
                ViewBag.DealerId = DealerId;
                return View(Dealer);
            }
            else
            {
                ViewBag.DealerId = "0";
                return View(new Dealers());                    
            }
        }
        [HttpPost]
        public ActionResult Maintenance(FormCollection formCollection)
        {
            ApplicationDBContext db = new ApplicationDBContext();
            if (formCollection["DealerId"] == "0")
            {
                Dealers Dealers = new Dealers();
                //Dealers.JoinDate = formCollection["JoinDate"];
                //Dealers.RecommendedBy = formCollection["RecommendedBy"];
                Dealers.DistributorId = Int32.Parse(formCollection["Distributor"]); // Send always 1 for now.. before insert 1 record with id 1 in zone table

                Dealers.ContactPerson = formCollection["Firstname"];
                //Dealers.Lastname = formCollection["Lastname"];
                Dealers.Name = formCollection["Companyname"];
                Dealers.Address.Address1 = formCollection["Address1"];
                Dealers.Address.Address2 = formCollection["Address2"];
                Dealers.Address.City = formCollection["City"];
                Dealers.Address.Zip = formCollection["Zip"];
                Dealers.Address.State = formCollection["State"];
                Dealers.Address.Country = formCollection["Country "];
                Dealers.Contact1.Mobile = formCollection["Mobilenumber1"];
                Dealers.Contact2.Mobile = formCollection["Mobilenumber2"];
                Dealers.Contact1.Phone = formCollection["Phonenumber1"];
                Dealers.Contact2.Phone = formCollection["Phonenumber2"];
                Dealers.Contact1.Email = formCollection["Email"];
                Dealers.Location = formCollection["Location"];
                //Dealers.StrengthFF = formCollection["StrengthFF"];
                //Dealers.Peeksaleperiod = formCollection["Peeksaleperiod"];
                //Dealers.Popularfestivals = formCollection["Popularfestivals"];
                //Dealers.Commands = formCollection["Commands"];
                //Dealers.Username = formCollection["Username"];
                //Dealers.Password = formCollection["Password"];
                db.Offices.AddObject(Dealers);

                return View("Index");
            }
            else
            {
                return View();
            }
        }
    }
}

LineFocus.Nikcron/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LineFocus.Nikcron.Controllers
{
    public class SalesController : Controller
    {
        //
        // GET: /Sales/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SalesMaintenance()
        {
            return View();
        }

    }
}

LineFocus.Nikcron/Controllers/StockController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LineFocus.Nikcron.Controllers
{
    public class StockController : Controller
    {
        //
        // GET: /Stock/

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult StockMaintenance()
        {
            return View();
        }

    }
}

LineFocus.Nikcron/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using DotNetOpenAuth.AspNet;
using Microsoft.Web.WebPages.OAuth;
using WebMatrix.WebData;
using LineFocus.Nikcron.Filters;
using LineFocus.Nikcron.Models;

namespace LineFocus.Nikcron.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class UserController : Controller
    {
        //
        // GET: /Account/Login

        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        //
        // POST: /Account/Login

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel model, string returnUrl)
        {
            if (ModelState.IsValid && WebSecurity.Login(model.UserName, model.Password, persistCookie: model.RememberMe))
            {
                return RedirectToLocal(returnUrl);
            }

            // If we got this far, something failed, redisplay form
            ModelState.AddModelError("", "The user name or password provided is incorrect.");
            return View(model);
        }

        //
        // POST: /Account/LogOff

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            WebSecurity.Logout();

            return RedirectToAction("Index", "Home");
        }

        //
        // GET: /Account/Register

        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }

        //
        // POST: /Account/Register

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Register(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                // Attempt to register the user
                try
                {
                    WebSecurity.CreateUserAndAccount(model.UserName, model.Password);
                    WebSecurity.Login(model.UserName, model.Password);
                    return RedirectToAction("Index", "Home");
                }
                catch (MembershipCreateUserException e)
                {
                    ModelState.AddModelError("", ErrorCodeToString(e.StatusCode));
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // POST: /Account/Disassociate

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Disassociate(string provider, string providerUserId)
        {
            string ownerAccount = OAuthWebSecurity.GetUserName(provider, providerUserId);
            ManageMessageId? message = null;

            // Only disassociate the account if the currently logged in user is the owner
            if (ownerAccount == User.Identity.Name)
            {
                // Use a transaction to prevent the user from deleting their last login credential
                using (var scope = new TransactionScope(TransactionScopeOption.Required, new TransactionOptions { IsolationLevel = IsolationLevel.Serializable }))
                {
                    bool hasLocalAccount = OAuthWebSecurity.HasLocalAccount(WebSecurity.GetUserId(User.Identity.Name));
                    if (hasLocalAccount || OAuthWebSecurity.GetAccountsFromUserName(User.Identity.Name).Count > 1)
                    {
                        OAuthWebSecurity.DeleteAccount(provider, providerUserId);
                        scope.Complete();
                        message = ManageMessageId.RemoveLoginSuccess;
                    }
                }
            }

            return RedirectToAction("Manage", new { Message = message });
        }

        //
        // GET: /Account/Manage

        public ActionResult Manage(ManageMessageId? message)
        {
            ViewBag.StatusMessage =
                message == ManageMessageId.ChangePasswordSuccess ? "Your password has been changed."
                : message == ManageMessageId.SetPasswordSuccess ? "Your password has been set."
                : message == ManageMessageId.RemoveLoginSuccess ? "The external login was removed."
                : "";
            ViewBag.HasLocalPassword = OAuthWebSecurity.HasLocalAccount(WebSecurity.GetUserId(User.Identity.Name));
            ViewBag.ReturnUrl = Url.Action("Manage");
            return View();
        }

        //
        // POST: /Account/Manage

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Manage(LocalPasswordModel model)
        {
            bool hasLocalAccount = OAuthWebSecurity.HasLocalAccount(WebSecurity.GetUserId(User.Identity.Name));
            ViewBag.HasLocalPassword = hasLocalAccount;
            ViewBag.ReturnUrl = Url.Action("Manage");
            if (hasLocalAccount)
            {
                if (ModelState.IsValid)
                {
                    // ChangePassword will throw an exception rather than return false in certain failure scenarios.
                    bool changePasswordSucceeded;
                    try
                    {
                        changePasswordSucceeded = WebSecurity.ChangePassword(User.Identity.Name, model.OldPassword, model.NewPassword);
                    }
                    catch (Exception)
                    {
                        changePasswordSucceeded = false;
                    }

                    if (changePasswordSucceeded)
                    {
                        return RedirectToAction("Manage", new { Message = ManageMessageId.ChangePasswordSuccess });
                    }
                    else
                    {
                        ModelState.AddModelError("", "The current password is incorrect or the new password is invalid.");
                    }
                }
            }
            else
            {
                // User does not have a local password so remove any validation errors caused by a missing
                // OldPassword field
                ModelState state = ModelState["OldPassword"];
                if (state != null)
                {
                    state.Errors.Clear();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        WebSecurity.CreateAccount(User.Identity.Name, model.NewPassword);
                        return RedirectToAction("Manage", new { Message = ManageMessageId.SetPasswordSuccess });
                    }
                    catch (Exception e)
                    {
                        ModelState.AddModelError("", e);
                    }
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // POST: /Account/ExternalLogin

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult ExternalLogin(string provider, string returnUrl)
        {
            return new ExternalLoginResult(provider, Url.Action("ExternalLoginCallback", new { ReturnUrl = returnUrl }));
        }

        //
        // GET: /Account/ExternalLoginCallback

        [AllowAnonymous]
        public ActionResult ExternalLoginCallback(string returnUrl)
        {
            AuthenticationResult result = OAuthWebSecurity.VerifyAuthentication(Url.Action("ExternalLoginCallback", new { ReturnUrl = returnUrl }));
            if (!result.IsSuccessful)
            {
                return RedirectToAction("ExternalLoginFailure");
            }

            if (OAuthWebSecurity.Login(result.Provider, result.ProviderUserId, createPersistentCookie: false))
            {
                return RedirectToLocal(returnUrl);
            }

            if (User.Identity.IsAuthenticated)
            {
                // If the current user is logged in add the new account
                OAuthWebSecurity.CreateOrUpdateAccount(result.Provider, result.ProviderUserId, User.Identity.Name);
                return RedirectToLocal(returnUrl);
            }
            else
            {
                // User is new, ask for their desired membership name
                string loginData = OAuthWebSecurity.SerializeProviderUserId(result.Provider, result.ProviderUserId);
                ViewBag.ProviderDisplayName = OAuthWebSecurity.GetOAuthClientData(result.Provider).DisplayName;
                ViewBag.ReturnUrl = returnUrl;
                return View("ExternalLoginConfirmation", new RegisterExternalLoginModel { UserName = result.UserName, ExternalLoginData = loginData });
            }
        }

        //
        // POST: /Account/ExternalLoginConfirmation

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult ExternalLoginConfirmation(RegisterExternalLoginModel model, string returnUrl)
        {
            string provider = null;
            string providerUserId = null;

            if (User.Identity.IsAuthenticated || !OAuthWebSecurity.TryDeserializeProviderUserId(model.ExternalLoginData, out provider, out providerUserId))
            {
                return RedirectToAction("Manage");
            }

            if (ModelState.IsValid)
            {
                // Insert a new user into the database
                using (UsersContext db = new UsersContext())
                {
                    UserProfile user = db.UserProfiles.FirstOrDefault(u => u.UserName.ToLower() == model.UserName.ToLower());
                    // Check if user already exists
                    if (user == null)
                    {
                        // Insert name into the profile table
                        db.UserProfiles.Add(new UserProfile { UserName = model.UserName });

LineFocus.Nikcron/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Nickron - @ViewBag.Title</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/AdminLTE")
        @Styles.Render("~/Content/jqWidget")
        @Styles.Render("~/Content/themes/base/css")

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryui")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/page")
        @Scripts.Render("~/bundles/jgWidget")
        @Scripts.Render("~/bundles/AdminLTEApp")
    </head>
<body class="skin-blue">
    <!-- header logo: style can be found in header.less -->
    <header class="header">
        <a href="@Url.Action("Index","Home",null)" class="logo"> <img src='@Url.Content("~/Images/header_logo.jpg")' width="171" height="51" alt="nikcron Logo" title="nikcron logo"> </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a>
            <div class="navbar-right">
                <ul class="nav navbar-nav">
                    <!-- Messages: style can be found in dropdown.less-->
                    <li class="dropdown messages-menu"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="fa fa fa-dashboard"></i> <span>Dashboard</span> </a> </li>
                    <!-- Notifications: style can be found in dropdown.less -->
                    <li class="dropdown notifications-menu">
        @*<a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="ion ion-android-contacts"></i> <span>Master</span> </a>
        <ul class="dropdown-menu">
            <li>
               
                <ul class="menu">
                    <li> <a href="#"> <i class="ion ion-ios7-people info"></i>Master 1</a> </li>
                    <li> <a href="#"> <i class="fa ion-ios7-people danger"></i>Master 2</a> </li>
                    <li> <a href="#"> <i class="fa ion-ios7-people warning"></i>Master 3</a> </li>
                    <li> <a href="#"> <i class="ion ion-ios7-people success"></i>Master 4</a> </li>
                    <li> <a href="#"> <i class="ion ion-ios7-people danger"></i>Master 5</a> </li>
                </ul>
            </li>
            <li class="footer"><a href="#">View all</a></li>
        </ul>*@
    </li>
    <!-- Tasks: style can be found in dropdown.less -->
    @*<li class="dropdown tasks-menu"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="fa ion-android-note"></i> <span>Report</span> </a> </li>*@
    <!-- User Account: style can be found in dropdown.less -->
    <li class="dropdown user user-menu">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="glyphicon glyphicon-user"></i> <span>Jane Doe <i class="caret"></i></span> </a>
        <ul class="dropdown-menu">
            <!-- Menu Body -->
            <li class="user-body">
                <div class="col-xs-4 text-center"> <a href="#"></a> </div>
                <div class="col-xs-4 text-center"> <a href="#"></a> </div>
                <div class="col-xs-4 text-center"> <a href="#"></a> </div>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
                <div class="pull-left"> <a href="#" class="btn btn-default btn-flat">Profile</a> </div>
                <div class="pull-right"> <a href="#" class="btn btn-default btn-flat">Sign out</a> </div>
            </li>
        </ul>
    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="wrapper row-offcanvas row-offcanvas-left">
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="left-side sidebar-offcanvas">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <!-- <div class="pull-left image">
                                            <img src="img/avatar3.png" class="img-circle" alt="User Image" />
                                        </div>-->
                    <div class="pull-left info">
                        <p>Welcome</p>
                        <a href="#">Admin</a>
                    </div>
                </div>
                <!-- search form -->
                <!--<form action="#" method="get" class="sidebar-form">
                                     <div class="input-group">
                                         <input type="text" name="q" class="form-control" placeholder="Search..."/>
                                         <span class="input-group-btn">
                                             <button type='submit' name='seach' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                                         </span>
                                     </div>
                                 </form>-->
                <!-- /.search form -->
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    <li class="active"> <a href="@Url.Action("Index","Home",null)"> <i class="fa fa-dashboard"></i> <span>Dashboard</span> </a> </li>
                    <li> <a href="@Url.Action("Index","Sales")"> <i class="fa fa-calendar"></i> <span>Sales</span> </a> </li>
                    <li> <a href="@Url.Action("Index", "Service")"> <i class="fa fa-envelope"></i> <span>Services</span></a> </li>
                    @*<li> <a href="@Url.Action("Index","Quotation")"> <i class="fa fa-edit"></i> <span>Quotes</span> <small class="badge pull-right bg-yellow">20</small> </a> </li>*@
                    <li> <a href="@Url.Action("Index", "PurchaseOrder")"> <i class="fa fa-envelope"></i> <span>Purchase Order</span></a> </li>
                    <li class="treeview">
                        <a href="#"> <i class="fa fa-table"></i> <span>Stock</span> <i class="fa fa-angle-left pull-right"></i> </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("StockMaintenance", "Stock")"><i class="fa fa-angle-double-right"></i> Add Stock</a></li>
                            <li><a href="@Url.Action("Index","Stock")"><i class="fa fa-angle-double-right"></i> View Stock</a></li>                            
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#"> <i class="fa fa-table"></i> <span>Company</span> <i class="fa fa-angle-left pull-right"></i> </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("Index","Company")"><i class="fa fa-angle-double-right"></i> Company</a></li>
                            <li><a href="@Url.Action("Index","Stockhouse")"><i class="fa fa-angle-double-right"></i> Stockhouses</a></li>
                            <li><a href="@Url.Action("Index","Distributor")"><i class="fa fa-angle-double-right"></i> Distrbutors</a></li>
                            <li><a href="@Url.Action("Index","Dealer")"><i class="fa fa-angle-double-right"></i> Dealers</a></li>
                            <li><a href="@Url.Action("Index","Retailer")"><i class="fa fa-angle-double-right"></i> Retailers</a></li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#"> <i class="fa fa-laptop"></i> <span>Products</span> <i class="fa fa-angle-left pull-right"></i> </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("Mobilephones", "Product")"><i class="fa fa-angle-double-right"></i> Mobilephones</a></li>
                            <li><a href="@Url.Action("Laptops","Product")"><i class="fa fa-angle-double-right"></i> Laptops</a></li>                            
                            <li><a href="@Url.Action("Tablets","Product")"><i class="fa fa-angle-double-right"></i> Tablets</a></li>
                            <li><a href="@Url.Action("Warranties","Product")"><i class="fa fa-angle-double-right"></i> Product Warranties</a></li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#"> <i class="fa fa-folder"></i> <span>Masters</span> <i class="fa fa-angle-left pull-right"></i> </a>
                        <ul class="treeview-menu">
                            
                            <li><a href="@Url.Action("ProductTypeMaintenance", "Master")"><i class="fa fa-angle-double-right"></i> Product Types</a></li>
                            <li><a href="@Url.Action("ManufactureMaintenance", "Master")"><i class="fa fa-angle-double-right"></i> Manufacturer Names</a></li>
                            <li><a href="@Url.Action("Index", "Master")"><i class="fa fa-angle-double-right"></i> Zones</a></li>
                            <li><a href="@Url.Action("CityMaintenance", "Master")"><i class="fa fa-angle-double-right"></i>City</a></li>
                            <li><a href="@Url.Action("StateMaintenance", "Master")"><i class="fa fa-angle-double-right"></i>State</a></li>
                            <li><a href="@Url.Action("CountryMaintenance", "Master")"><i class="fa fa-angle-double-right"></i>Country</a></li>                          
                            
                            <li><a href="@Url.Action("ServiceTypeMaintenance", "Master")"><i class="fa fa-angle-double-right"></i> Service Types</a></li>                            
                           
                            
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#"> <i class="fa fa-user"></i> <span>Users</span> <i class="fa fa-angle-left pull-right"></i> </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("Index", "User")"><i class="fa fa-angle-double-right"></i>Nikcron Office Users</a></li>                                                      
                            <li><a href="@Url.Action("Roles", "User")"><i class="fa fa-angle-double-right"></i> Roles</a></li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#"> <i class="fa fa-bar-chart-o"></i> <span>Reports</span> <i class="fa fa-angle-left pull-right"></i> </a>
                        <ul class="treeview-menu"></ul>
                    </li>
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Right side column. Contains the navbar and content of the page -->
        <aside class="right-side">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1> @ViewBag.Header <small>@ViewBag.Caption</small> </h1>
                <ol class="breadcrumb">
                    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                    <li class="active">Dashboard</li>
                </ol>
            </section>
            <!-- Main content -->
            <section class="content">
                <div class="row" style="padding-left: 10px;">
                    @RenderBody()
                </div>
                <!-- /.row -->
                <!-- top row -->
            </section>
            <!-- /.content -->
        </aside>
        <!-- /.right-side -->
    </div>
    
</body>
</html>